### ISSUE TITLE
Add serialization for AltchaChallenge

### ISSUE THREAD

**Issue by klemmchr** [ixnas/altcha-dotnet#1]
First of all thank you for this great library.

We're using it for invisible captchas on our client without the Altcha widget. What I dislike is that the serialization and deserialization is missing and is expected to be handled by the user of the library. I ended up writing my own service that serializes and base64 encodes the challenge to make it easy to handle when sending it back and forth but I believe that this should be part of this library instead since this method is quite universal.

This is my current implementation

```csharp
public static class CaptchaSerializer
{
    public static string Serialize(AltchaChallenge challenge)
    {
        var json = JsonSerializer.SerializeToUtf8Bytes(
            challenge,
            DefaultJsonSerializerOptions.Instance
        );
        var encoded = Convert.ToBase64String(json);
        return encoded.Replace('+', '-').Replace('/', '_').Replace('=', '.');
    }

    public static AltchaChallenge Deserialize(string serialized)
    {
        var padded = serialized.Replace('-', '+').Replace('_', '/').Replace('.', '=');
        var json = Convert.FromBase64String(padded);
        return JsonSerializer.Deserialize<AltchaChallenge>(
            json,
            DefaultJsonSerializerOptions.Instance
        )!;
    }
}
```

**Comment by ixnas** [comment]
Hi there! I'm glad the library is useful for you!

The public API of this library purposefully designed with just the plain objects. The main reason for this is that the user of the library can choose whatever data format/encoding/structure they like to use. I don't want this library to make that decision for anyone, and I can't support every possible file format configuration.

Even when it comes to just base64, there are different padding rules to choose from and various (non-standard) ways of making it web safe, which you seem to have implemented a certain way.

With the current design, you can either convert the plain object to whatever you like, and transport it however you like, or (if you're building an ASP.NET web API) you just return the object and the controller will handle the serialization in a way that's immediately compatible with the front-end widget.

Of course you can always write extension methods for `AltchaService` if you don't want to put your serialization in a different service.

I hope I could be of help to you!
