### ISSUE TITLE
Translations (Localization)

### ISSUE THREAD

**Issue by Deizo** [ixnas/altcha-dotnet#2]
Hello!

In the official documentation, I've found a way to translate the texts. With this lib, is there a way too?

https://altcha.org/docs/widget-customization/#localization

**Comment by ixnas** [comment]
Hi there!

This library by itself doesn't have any user facing text to translate. You're still expected to use ALTCHA's official front-end widget if you're going to use my library in your back-end.

So for translating user facing text, that method from ALTCHA's official documentation still applies.

I hope I could be of any help, and thank you for taking an interest in this project!
